[package]
name = "machine_learning"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
env = { path = "../env"}
rayon = "1.10.0"
